# Generated by Django 5.1 on 2024-08-12 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(default='rawmaterial', max_length=50)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reorder_level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_id', models.CharField(max_length=100)),
                ('product_id', models.JSONField(blank=True, default=list)),
                ('quantity_sold', models.JSONField(blank=True, default=list)),
                ('sales_amount', models.JSONField(blank=True, default=list)),
                ('sales_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SaleStocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_id', models.CharField(max_length=100)),
                ('product_id', models.JSONField(blank=True, default=list)),
                ('quantity_obtained', models.JSONField(blank=True, default=list)),
                ('stock_amount', models.JSONField(blank=True, default=list)),
                ('stock_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('Addition', 'Addition'), ('Removal', 'Removal'), ('Update', 'Update')], max_length=10)),
                ('quantity', models.PositiveIntegerField()),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryitem')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=255, null=True)),
                ('quantityProduced', models.PositiveIntegerField()),
                ('quantityUsed', models.JSONField(blank=True, default=list)),
                ('productionDate', models.DateTimeField(auto_now_add=True)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('rawMaterials', models.ManyToManyField(blank=True, related_name='production_records', to='inventory.inventoryitem')),
            ],
        ),
    ]
