# Generated by Django 5.1 on 2024-08-13 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesStockTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('Addition', 'Addition'), ('Update', 'Update')], max_length=10)),
                ('product_id', models.JSONField(blank=True, default=list)),
                ('quantity_obtained', models.JSONField(blank=True, default=list)),
                ('stock_amount', models.JSONField(blank=True, default=list)),
                ('stock_date', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True)),
                ('sale_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.salestocks')),
            ],
        ),
    ]
