# Generated by Django 5.1 on 2024-08-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_remove_inventorytransaction_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionrecord',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
