# Generated by Django 5.1 on 2024-08-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_productionrecord_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salesstocktransactions',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salestocks',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
