# Generated by Django 5.1 on 2024-08-13 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_salesstocktransactions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='branch_id',
        ),
        migrations.RemoveField(
            model_name='salestocks',
            name='branch_id',
        ),
    ]
