# Generated by Django 5.1 on 2024-08-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_sales_branch_id_remove_salestocks_branch_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='product_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='quantity_sold',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sales_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salesstocktransactions',
            name='product_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='salesstocktransactions',
            name='quantity_obtained',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='salesstocktransactions',
            name='stock_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salestocks',
            name='product_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='salestocks',
            name='quantity_obtained',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='salestocks',
            name='stock_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
