# Generated by Django 5.1 on 2024-08-15 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auditlog_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('inventory_representative', 'Inventory Representative'), ('production_representative', 'Production Representative'), ('sales_representative', 'Sales Representative')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=50),
        ),
    ]
