# Generated by Django 5.1 on 2024-08-15 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_userprofile_role_alter_userprofile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('inventory_representative', 'Inventory Representative'), ('production_representative', 'Production Representative'), ('sales_representative', 'Sales Representative')], default='sales_representative', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=50),
        ),
    ]
