# Generated by Django 5.1 on 2024-08-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_inventorytransaction_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorytransaction',
            name='user',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
